### ISSUE TITLE
Popular tags not working

### ISSUE THREAD

**Issue by ritwik12** [up-for-grabs/up-for-grabs.net#1150]
Popular tags again seems to be not working.

Reproduction steps:

 - browse to `up-for-grabs.net`
 - click on `javascript` popular tag
 
Expected behaviour:

 - list of projects relevant to selected tag displayed
 
Actual behaviour:

 - no projects displayed

See #1121 and #1116  for related discussions

**Comment by shiftkey** [comment]
Popular tags should be fixed in #1166, but I'm not sure about the fix for the tags in each item - it looks like it's generating an incompatible URL that the app doesn't handle.

**Comment by Priyanka488** [comment]
@ritwik12 @shiftkey Is the issue still available ? may i work on it ?

**Comment by shiftkey** [comment]
@Priyanka488 I believe this has been resolved by #1179 (which I meant to merge earlier but forgot), and this should be deployed in a couple of minutes.

Please drop a comment back in here if you still encounter the issue.
