### ISSUE TITLE
Filter should be an AND not an OR

### ISSUE THREAD

**Issue by FakeHaacked** [up-for-grabs/up-for-grabs.net#250]
Hi all!

I was trying to combine filters and all it does in the search box is add _more_ results to the list. That seems to be not very useful. The reason I'm adding more filters is to narrow down the results, not expand them.

**Comment by shiftkey** [comment]
:thumbsup:

**Comment by shubheksha** [comment]
Any guidelines on what needs to be done to fix this?

**Comment by shiftkey** [comment]
After a quick glance of projectsService.js, I think this is hiding in [applyTagsFilter](https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/javascripts/projectsService.js#L2-L23) but I'm not 100% sure.

cc @chandu @dahlbyk for thoughts.

**Comment by dahlbyk** [comment]
Yep, the [`projectNames`](https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/javascripts/projectsService.js#L15-L18) list is built up as a distinct list of projects that "hit" on any of the tags. That variable can probably be discarded in favor of updating the `filter` clause below to check that the project includes all requested tags.

**Comment by shiftkey** [comment]
:ok_hand:

**Comment by chandu** [comment]
@dahlbyk @shiftkey Agreed. I will send a pull request with the required changes.

**Comment by ritwik12** [comment]
PR #729 is able to solve this issue but the problem is that it works when you type a keyword and hit enter, but not when you type the keyword and then click the item from the drop-down.
@shiftkey  and @dahlbyk

**Comment by erlend-sh** [comment]
I just ran into this today. I want to link newcomers in the Rust gamedev community to a tag combination like 
`https://up-for-grabs.net/#/tags/gamedev%2Crust`.

**Comment by wolffles** [comment]
I think this can be closed its a duplicate, and the issue might already be fixed

**Comment by erlend-sh** [comment]
Duplicate of which issue though? And if it’s solved, could you please share an example of how to do an AND filter?

**Comment by wolffles** [comment]
the duplicate is here: https://github.com/up-for-grabs/up-for-grabs.net/issues/1115 
I was on the site yesterday, the filters are currently 'and'. They add upon each other already, if you select a label, then click on a popular tag it chooses all the labels with that tag... however whoever updated it missed the tags filter box which i then fixed in my pull request for the other issue. https://github.com/up-for-grabs/up-for-grabs.net/pull/1135

**Comment by deltafactory** [comment]
Addressed by #1135?

**Comment by shiftkey** [comment]
@deltafactory I'm not 100% sure - I thought I could still reproduce it. I have #729 in my backlog to review which is believed to be a fix, so I'll check again when I get to that.
